#!/usr/bin/env bash

# alacritty
rm -rf ~/.alacritty.yml
ln -sf ~/dotfiles/alacritty.yml ~/.alacritty.yml

# tmux
rm -rf ~/.tmux.conf
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf

# zsh
rm -rf ~/.zshrc
ln -sf ~/dotfiles/zshrc ~/.zshrc

# nvim
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/ftdetect

# link wholesale
for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/$f ~/.config/nvim/$f
done
rm -rf ~/.config/nvim/coc-settings.json
ln -s ~/dotfiles/coc-settings.json ~/.config/nvim/coc-settings.json
